name: Terraform Deploy

on:
  push:
    branches:
      - '**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: eu-west-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./infra

      - name: Terraform Plan
        id: tf-plan
        run: terraform plan
        working-directory: ./infra
        if: github.ref != 'refs/heads/main'

      - name: Terraform Apply
        id: tf-apply
        run: terraform apply -auto-approve
        working-directory: ./infra
        if: github.ref == 'refs/heads/main'
